import Head from 'next/head'
import Image from 'next/image'
import CategoryBar from '../lib/components/site/CategoryBar'
import Feed from '../lib/components/site/Feed'
import Nav from '../lib/components/site/Nav'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className='flex'>
        <CategoryBar />
        <Feed />
      </main>
    </div>
  )
}
