import Head from "next/head";
import CategoryBar from "../lib/components/CategoryBar";
import Feed from "../lib/components/Feed";
import Nav from "../lib/components/Nav";
import { useState } from "react";

export default function Home() {
  const [selected, setSelected] = useState("latest");
  const [menuToggle, setMenuToggle] = useState(true);

  const tech = "tech";
  const latest = "latest";
  const misc = "misc";
  const travel = "travel";
  const media = "media";
  const health = "health";
  const music = "music";

  const menuToggleFunc = () => {
    setMenuToggle(!menuToggle);
  };

  return (
    <div className="scrollbar-none">
      <Head>
        <title>Long Addition</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav
        menuToggle={menuToggle}
        setMenuToggle={setMenuToggle}
        menuToggleFunc={menuToggleFunc}
      />
      <div className="flex scrollbar-none">
        <CategoryBar
          selected={selected}
          setSelected={setSelected}
          misc={misc}
          tech={tech}
          lates={latest}
          travel={travel}
          media={media}
          health={health}
          music={music}
        />
        <Feed
          selected={selected}
          misc={misc}
          tech={tech}
          lates={latest}
          travel={travel}
          media={media}
          health={health}
          music={music}
        />
      </div>
    </div>
  );
}
